version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  api:
    container_name: parking_tracker_be
    build:
      context: .
      target: development
    image: parking_tracker_be
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: development
      DATABASE_HOST: db
      DB_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
      DATABASE_SYNC: 'true'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - db
      - redis
volumes:
  db:
    driver: local
  redis:
    driver: local
